"""All SQLAlchemy models. Importing this package registers every table on ``Base.metadata``
(Alembic's env.py relies on that)."""

from autora.db.models.agents import ActivityState, Agent, AgentActivity, AgentStatus
from autora.db.models.company import (
    CommandOutcome,
    CommandRecord,
    Company,
    CompanyGoal,
    CompanyPolicy,
    CompanyStatus,
    CompanyType,
    Cycle,
    CycleStage,
    GoalLevel,
    GoalStatus,
    KpiScope,
    KpiSnapshot,
)
from autora.db.models.finance import (
    Budget,
    BudgetPeriod,
    Transaction,
    TransactionKind,
    TransactionSource,
)
from autora.db.models.model_calls import CostReservation, ModelCall, ModelCallStatus
from autora.db.models.organization import (
    BusinessUnit,
    BusinessUnitState,
    Department,
    Product,
    ProductState,
    Role,
)
from autora.db.models.projects import Project, ProjectState
from autora.db.models.runtime import (
    Approval,
    ApprovalKind,
    ApprovalState,
    EventRecord,
    PolicyDecision,
    Schedule,
    StateTransition,
)
from autora.db.models.tasks import (
    AGENT_RUN_TERMINAL,
    AgentRun,
    AgentRunState,
    AgentStep,
    StepKind,
    Task,
    TaskState,
    WorkflowRun,
    WorkflowRunState,
)

__all__ = [
    "AGENT_RUN_TERMINAL",
    "ActivityState",
    "Agent",
    "AgentActivity",
    "AgentRun",
    "AgentRunState",
    "AgentStep",
    "AgentStatus",
    "Approval",
    "ApprovalKind",
    "ApprovalState",
    "Budget",
    "BusinessUnit",
    "BusinessUnitState",
    "BudgetPeriod",
    "Company",
    "CompanyGoal",
    "CompanyPolicy",
    "CompanyStatus",
    "CompanyType",
    "CommandOutcome",
    "CommandRecord",
    "CostReservation",
    "Department",
    "Cycle",
    "CycleStage",
    "EventRecord",
    "GoalLevel",
    "KpiScope",
    "KpiSnapshot",
    "GoalStatus",
    "ModelCall",
    "ModelCallStatus",
    "PolicyDecision",
    "Product",
    "ProductState",
    "Project",
    "ProjectState",
    "Role",
    "Schedule",
    "StateTransition",
    "StepKind",
    "Task",
    "TaskState",
    "Transaction",
    "TransactionKind",
    "TransactionSource",
    "WorkflowRun",
    "WorkflowRunState",
]
