"""work execution tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-17 11:07:48.729761+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("template_name", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("state", sa.Text(), server_default="RUNNING", nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_workflow_runs_state_valid"),
        ),
        sa.CheckConstraint(
            "template_name ~ '^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$'",
            name=op.f("ck_workflow_runs_template_name_format"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_workflow_runs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_workflow_runs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    op.create_index(
        "ix_workflow_runs_company_state", "workflow_runs", ["company_id", "state"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("required_role", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="PENDING", nullable=False),
        sa.Column(
            "depends_on",
            postgresql.ARRAY(sa.UUID()),
            server_default=sa.text("'{}'::uuid[]"),
            nullable=False,
        ),
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema_ref", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("budget_usd", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state = 'RUNNING') = (lease_owner IS NOT NULL AND lease_until IS NOT NULL)",
            name=op.f("ck_tasks_lease_iff_running"),
        ),
        sa.CheckConstraint("name ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_tasks_name_format")),
        sa.CheckConstraint(
            "required_role ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_tasks_required_role_format")
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'READY', 'RUNNING', 'WAITING_APPROVAL', 'BLOCKED_BUDGET', 'SUCCEEDED', 'FAILED', 'CANCELLED')",
            name=op.f("ck_tasks_state_valid"),
        ),
        sa.CheckConstraint(
            "attempt >= 0 AND attempt <= max_attempts", name=op.f("ck_tasks_attempt_within_max")
        ),
        sa.CheckConstraint(
            "budget_usd IS NULL OR budget_usd >= 0", name=op.f("ck_tasks_budget_non_negative")
        ),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_tasks_max_attempts_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_tasks_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_tasks_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_tasks_workflow_run_id_workflow_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("ix_tasks_company_state", "tasks", ["company_id", "state"], unique=False)
    op.create_index(
        "ix_tasks_ready_queue",
        "tasks",
        ["company_id", "priority", "created_at"],
        unique=False,
        postgresql_where=sa.text("state = 'READY'"),
    )
    op.create_index(
        "ix_tasks_running_lease",
        "tasks",
        ["lease_until"],
        unique=False,
        postgresql_where=sa.text("state = 'RUNNING'"),
    )
    op.create_index("ix_tasks_workflow_run", "tasks", ["workflow_run_id"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("state", sa.Text(), server_default="CREATED", nullable=False),
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("handoff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
        sa.Column("tokens_in", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("steps_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(state IN ('COMPLETED', 'FAILED', 'ABORTED')) = (finished_at IS NOT NULL)",
            name=op.f("ck_agent_runs_finished_iff_terminal"),
        ),
        sa.CheckConstraint(
            "state IN ('CREATED', 'RUNNING', 'WAITING_APPROVAL', 'EVALUATING', 'REPAIRING', 'COMPLETED', 'FAILED', 'ABORTED')",
            name=op.f("ck_agent_runs_state_valid"),
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_agent_runs_attempt_positive")),
        sa.CheckConstraint(
            "cost_usd >= 0 AND tokens_in >= 0 AND tokens_out >= 0 AND steps_count >= 0",
            name=op.f("ck_agent_runs_usage_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_runs_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_agent_runs_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_agent_runs_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
        sa.UniqueConstraint("task_id", "attempt", name=op.f("uq_agent_runs_task_id_attempt")),
    )
    op.create_index(
        "ix_agent_runs_agent_created", "agent_runs", ["agent_id", "created_at"], unique=False
    )
    op.create_table(
        "agent_steps",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prompt_hash", sa.Text(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("blob_key", sa.Text(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('think', 'act', 'observe', 'evaluate', 'repair')",
            name=op.f("ck_agent_steps_kind_valid"),
        ),
        sa.CheckConstraint("cost_usd >= 0", name=op.f("ck_agent_steps_cost_non_negative")),
        sa.CheckConstraint("seq >= 0", name=op.f("ck_agent_steps_seq_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_agent_steps_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_agent_steps_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_steps")),
        sa.UniqueConstraint("run_id", "seq", name=op.f("uq_agent_steps_run_id_seq")),
    )
    op.create_foreign_key(
        op.f("fk_projects_created_by_run_id_agent_runs"),
        "projects",
        "agent_runs",
        ["created_by_run_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###

    # The run trace is audit data: steps are append-only (function defined in 0002).
    op.execute(
        "CREATE TRIGGER agent_steps_append_only BEFORE UPDATE OR DELETE ON agent_steps "
        "FOR EACH ROW EXECUTE FUNCTION autora_forbid_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS agent_steps_append_only ON agent_steps")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_created_by_run_id_agent_runs"), "projects", type_="foreignkey"
    )
    op.drop_table("agent_steps")
    op.drop_index("ix_agent_runs_agent_created", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index("ix_tasks_workflow_run", table_name="tasks")
    op.drop_index(
        "ix_tasks_running_lease", table_name="tasks", postgresql_where=sa.text("state = 'RUNNING'")
    )
    op.drop_index(
        "ix_tasks_ready_queue", table_name="tasks", postgresql_where=sa.text("state = 'READY'")
    )
    op.drop_index("ix_tasks_company_state", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_workflow_runs_company_state", table_name="workflow_runs")
    op.drop_table("workflow_runs")
    # ### end Alembic commands ###
