"""model calls

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-17 11:25:04.837801+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_calls",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("capability", sa.Text(), nullable=False),
        sa.Column("alias", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("tokens_in", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tokens_out", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("cache_write_tokens", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "cost_usd", sa.Numeric(precision=18, scale=6), server_default="0", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('ok', 'error')", name=op.f("ck_model_calls_status_valid")),
        sa.CheckConstraint(
            "tokens_in >= 0 AND tokens_out >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0 AND cost_usd >= 0 AND latency_ms >= 0",
            name=op.f("ck_model_calls_usage_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_model_calls_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_model_calls_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_model_calls_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_model_calls_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_model_calls_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_calls")),
    )
    op.create_index(
        "ix_model_calls_company_created", "model_calls", ["company_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_model_calls_project_created", "model_calls", ["project_id", "created_at"], unique=False
    )
    op.create_index("ix_model_calls_run", "model_calls", ["run_id"], unique=False)
    op.create_index("ix_model_calls_task", "model_calls", ["task_id"], unique=False)
    # ### end Alembic commands ###

    # Cost ledger: append-only (function defined in 0002).
    op.execute(
        "CREATE TRIGGER model_calls_append_only BEFORE UPDATE OR DELETE ON model_calls "
        "FOR EACH ROW EXECUTE FUNCTION autora_forbid_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS model_calls_append_only ON model_calls")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_calls_task", table_name="model_calls")
    op.drop_index("ix_model_calls_run", table_name="model_calls")
    op.drop_index("ix_model_calls_project_created", table_name="model_calls")
    op.drop_index("ix_model_calls_company_created", table_name="model_calls")
    op.drop_table("model_calls")
    # ### end Alembic commands ###
