"""Generate the TypeScript contract for events: zod v4 schemas + inferred types (T-108).

Pydantic is the single source of truth. This module converts the JSON Schema pydantic emits (in
serialization mode, i.e. what actually goes over the wire) into zod source. Pydantic only emits
a small subset of JSON Schema for our models, and anything outside that subset fails loudly
instead of producing a silently wrong validator.

Frontend tolerance rules (logs/3d-office/03_EVENT_MODEL.md §7) are encoded here:
- objects are ``z.object`` (unknown keys are stripped, not rejected), so adding a payload field
  never breaks an older client;
- unknown ``event_type`` values fail ``EventEnvelope.safeParse`` and the reducer ignores them.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any

from pydantic import BaseModel

from autora.runtime.events.schema import EventEnvelope, EventPayload, Persistence

HEADER = (
    "// GENERATED by `make gen-schema` from autora.runtime.events (pydantic). Do not edit.\n"
    "// Source of truth: backend/autora/**/events.py\n"
)

_ENVELOPE_SPECIAL = ("event_type", "schema_version", "payload")


class CodegenError(Exception):
    pass


def _pascal(event_type: str) -> str:
    return "".join(part.capitalize() for part in event_type.lower().split("_"))


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


class _Emitter:
    def __init__(self) -> None:
        self.defs: dict[str, dict[str, Any]] = {}

    # --- $defs -----------------------------------------------------------------------------

    def collect_defs(self, schema: dict[str, Any], owner: str) -> None:
        for name, definition in schema.get("$defs", {}).items():
            existing = self.defs.get(name)
            if existing is not None and existing != definition:
                raise CodegenError(
                    f"two different models are both named {name!r} (seen again in {owner}); "
                    "rename one so the generated TypeScript names stay unique"
                )
            self.defs[name] = definition

    def ordered_defs(self) -> list[str]:
        order: list[str] = []
        visiting: set[str] = set()

        def visit(name: str) -> None:
            if name in order:
                return
            if name in visiting:
                raise CodegenError(f"recursive model {name!r} is not supported")
            visiting.add(name)
            for ref in sorted(_refs(self.defs[name])):
                visit(ref)
            visiting.discard(name)
            order.append(name)

        for name in sorted(self.defs):
            visit(name)
        return order

    # --- schema -> zod ---------------------------------------------------------------------

    def zod(self, node: Mapping[str, Any]) -> str:
        known = {
            "title", "description", "default", "$defs", "type", "format", "pattern", "minimum",
            "maximum", "exclusiveMinimum", "exclusiveMaximum", "minLength", "maxLength", "enum",
            "const", "anyOf", "items", "properties", "required", "additionalProperties", "$ref",
        }  # fmt: skip
        unknown = set(node) - known
        if unknown:
            raise CodegenError(f"unsupported JSON Schema keywords {sorted(unknown)} in {node}")

        if "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        if "const" in node:
            return f"z.literal({_json(node['const'])})"
        if "enum" in node:
            values = node["enum"]
            if all(isinstance(v, str) for v in values):
                return f"z.enum([{', '.join(_json(v) for v in values)}])"
            return f"z.union([{', '.join(f'z.literal({_json(v)})' for v in values)}])"
        if "anyOf" in node:
            options = node["anyOf"]
            non_null = [o for o in options if o.get("type") != "null"]
            if len(non_null) == 1 and len(options) == 2:
                return f"{self.zod(non_null[0])}.nullable()"
            return f"z.union([{', '.join(self.zod(o) for o in options)}])"

        kind = node.get("type")
        if kind is None:
            return "z.unknown()"
        if kind == "string":
            fmt = node.get("format")
            if fmt == "uuid":
                expr = "z.uuid()"
            elif fmt == "date-time":
                expr = "z.iso.datetime({ offset: true })"
            elif fmt == "date":
                expr = "z.iso.date()"
            elif fmt is None:
                expr = "z.string()"
            else:
                raise CodegenError(f"unsupported string format {fmt!r}")
            if "pattern" in node:
                expr += f".regex(new RegExp({_json(node['pattern'])}))"
            if "minLength" in node:
                expr += f".min({node['minLength']})"
            if "maxLength" in node:
                expr += f".max({node['maxLength']})"
            return expr
        if kind in ("integer", "number"):
            expr = "z.number().int()" if kind == "integer" else "z.number()"
            for keyword, method in (
                ("minimum", "min"),
                ("maximum", "max"),
                ("exclusiveMinimum", "gt"),
                ("exclusiveMaximum", "lt"),
            ):
                if keyword in node:
                    expr += f".{method}({node[keyword]})"
            return expr
        if kind == "boolean":
            return "z.boolean()"
        if kind == "null":
            return "z.null()"
        if kind == "array":
            return f"z.array({self.zod(node.get('items', {}))})"
        if kind == "object":
            properties = node.get("properties")
            if not properties:
                return "z.record(z.string(), z.unknown())"
            required = set(node.get("required", []))
            lines = [
                f"  {name}: {self.field(schema, name in required)},"
                for name, schema in properties.items()
            ]
            return "z.object({\n" + "\n".join(lines) + "\n})"
        raise CodegenError(f"unsupported JSON Schema type {kind!r}")

    def field(self, schema: Mapping[str, Any], required: bool) -> str:
        expr = self.zod(schema)
        if required:
            return expr
        if "default" not in schema:
            return f"{expr}.optional()"
        default = schema["default"]
        if isinstance(default, list | dict):
            return f"{expr}.default(() => ({_json(default)}))"
        return f"{expr}.default({_json(default)})"


def _refs(node: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(node, dict):
        if "$ref" in node:
            found.add(node["$ref"].rsplit("/", 1)[-1])
        for value in node.values():
            found |= _refs(value)
    elif isinstance(node, list):
        for value in node:
            found |= _refs(value)
    return found


def _schema(model: type[BaseModel]) -> dict[str, Any]:
    return model.model_json_schema(mode="serialization", ref_template="#/$defs/{model}")


def generate(registry: Mapping[tuple[str, int], type[EventPayload]]) -> tuple[str, dict[str, Any]]:
    """Return (TypeScript source, JSON catalog) for the given payload registry."""
    emitter = _Emitter()

    envelope_schema = _schema(EventEnvelope)
    emitter.collect_defs(envelope_schema, "EventEnvelope")
    emitter.defs.pop("EventPayload", None)  # replaced by concrete payloads per event type

    entries = sorted(registry.items())
    payload_schemas: dict[tuple[str, int], dict[str, Any]] = {}
    for (event_type, version), cls in entries:
        schema = _schema(cls)
        emitter.collect_defs(schema, cls.__qualname__)
        payload_schemas[(event_type, version)] = schema

    out: list[str] = [HEADER, 'import { z } from "zod";\n']

    out.append("// --- shared models " + "-" * 70 + "\n")
    for name in emitter.ordered_defs():
        out.append(f"export const {name} = {emitter.zod(emitter.defs[name])};")
        out.append(f"export type {name} = z.infer<typeof {name}>;\n")

    envelope_fields = {
        name: schema
        for name, schema in envelope_schema["properties"].items()
        if name not in _ENVELOPE_SPECIAL
    }
    envelope_required = set(envelope_schema.get("required", []))
    field_lines = [
        f"  {name}: {emitter.field(schema, name in envelope_required)},"
        for name, schema in envelope_fields.items()
    ]
    out.append("// --- envelope " + "-" * 75 + "\n")
    out.append("const envelopeFields = {\n" + "\n".join(field_lines) + "\n};\n")

    out.append("// --- events " + "-" * 77 + "\n")
    by_type: dict[str, list[str]] = {}
    for event_type, version in (key for key, _ in entries):
        base = f"{_pascal(event_type)}V{version}"
        schema = dict(payload_schemas[(event_type, version)])
        schema.pop("$defs", None)
        out.append(f"export const {base}Payload = {emitter.zod(schema)};")
        out.append(f"export type {base}Payload = z.infer<typeof {base}Payload>;")
        out.append(
            f"export const {base}Event = z.object({{\n"
            f"  ...envelopeFields,\n"
            f"  event_type: z.literal({_json(event_type)}),\n"
            f"  schema_version: z.literal({version}),\n"
            f"  payload: {base}Payload,\n"
            f"}});\n"
        )
        by_type.setdefault(event_type, []).append(f"{base}Event")

    options: list[str] = []
    for event_type in sorted(by_type):
        versions = by_type[event_type]
        if len(versions) == 1:
            options.append(versions[0])
        else:
            options.append(f'z.discriminatedUnion("schema_version", [{", ".join(versions)}])')
    out.append(
        'export const EventEnvelope = z.discriminatedUnion("event_type", [\n'
        + "".join(f"  {option},\n" for option in options)
        + "]);"
    )
    out.append("export type EventEnvelope = z.infer<typeof EventEnvelope>;")
    out.append('export type EventType = EventEnvelope["event_type"];')
    out.append(
        "export type EventOf<T extends EventType> = Extract<EventEnvelope, { event_type: T }>;\n"
    )

    types = sorted(by_type)
    ephemeral = sorted({t for (t, _), cls in entries if cls.persistence is Persistence.EPHEMERAL})
    out.append(
        "export const EVENT_TYPES = [\n"
        + "".join(f"  {_json(t)},\n" for t in types)
        + "] as const satisfies readonly EventType[];\n"
    )
    out.append(
        "export const EPHEMERAL_EVENT_TYPES: ReadonlySet<EventType> = new Set<EventType>([\n"
        + "".join(f"  {_json(t)},\n" for t in ephemeral)
        + "]);"
    )
    source = "\n".join(out) + "\n"

    catalog = {
        "$comment": HEADER.strip().replace("// ", ""),
        "envelope": envelope_schema,
        "events": {
            event_type: {
                str(version): {
                    "persistence": cls.persistence.value,
                    "payload": payload_schemas[(event_type, version)],
                }
                for (t, version), cls in entries
                if t == event_type
            }
            for event_type in types
        },
    }
    return source, catalog
