"""company core and fsm audit

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-16 09:46:33.383260+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

APPEND_ONLY_TABLES = ("transactions", "state_transitions")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column(
            "strategy_doc",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'", name=op.f("ck_companies_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'archived')", name=op.f("ck_companies_status_valid")
        ),
        sa.CheckConstraint(
            "type IN ('newsroom', 'saas', 'research', 'ecommerce', 'software_studio')",
            name=op.f("ck_companies_type_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_table(
        "agents",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("avatar_key", sa.Text(), server_default="default", nullable=False),
        sa.Column(
            "capabilities",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "tools",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "permissions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "model_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "budget",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_agents_role_format")),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'retired')", name=op.f("ck_agents_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_agents_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agents")),
        sa.UniqueConstraint(
            "company_id", "display_name", name=op.f("uq_agents_company_id_display_name")
        ),
    )
    op.create_table(
        "company_goals",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("parent_goal_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("target", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("current", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('annual', 'quarter', 'cycle')", name=op.f("ck_company_goals_level_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'achieved', 'missed', 'cancelled')",
            name=op.f("ck_company_goals_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_company_goals_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["parent_goal_id"],
            ["company_goals.id"],
            name=op.f("fk_company_goals_parent_goal_id_company_goals"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_goals")),
    )
    op.create_index(
        op.f("ix_company_goals_company_id"), "company_goals", ["company_id"], unique=False
    )
    op.create_table(
        "company_policies",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key ~ '^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$'",
            name=op.f("ck_company_policies_key_format"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_company_policies_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_policies")),
        sa.UniqueConstraint("company_id", "key", name=op.f("uq_company_policies_company_id_key")),
    )
    op.create_table(
        "projects",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default="PROPOSED", nullable=False),
        sa.Column("kill_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by_run_id", sa.UUID(), nullable=True),
        sa.Column("approved_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('PROPOSED', 'APPROVED', 'ACTIVE', 'PAUSED', 'KILLED', 'COMPLETED', 'REJECTED')",
            name=op.f("ck_projects_state_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('PROPOSED', 'REJECTED') OR kill_criteria IS NOT NULL",
            name=op.f("ck_projects_kill_criteria_required_once_approved"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_projects_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_company_id"), "projects", ["company_id"], unique=False)
    op.create_table(
        "state_transitions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.Text(), nullable=False),
        sa.Column("to_state", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_state_transitions_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_state_transitions")),
    )
    op.create_index(
        "ix_state_transitions_entity",
        "state_transitions",
        ["entity_type", "entity_id", "at"],
        unique=False,
    )
    op.create_table(
        "budgets",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("period", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("hard_cap", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_budgets_currency_format")),
        sa.CheckConstraint(
            "period IN ('cycle', 'day', 'month')", name=op.f("ck_budgets_period_valid")
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_budgets_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_budgets_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_budgets_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
        sa.UniqueConstraint(
            "company_id",
            "project_id",
            "period",
            name=op.f("uq_budgets_company_id_project_id_period"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.Text(), server_default="USD", nullable=False),
        sa.Column("ref_type", sa.Text(), nullable=True),
        sa.Column("ref_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_transactions_category_format")
        ),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_transactions_currency_format")),
        sa.CheckConstraint(
            "kind IN ('expense', 'revenue', 'capital_in', 'capital_out', 'transfer')",
            name=op.f("ck_transactions_kind_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('system', 'human', 'integration')",
            name=op.f("ck_transactions_source_valid"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_transactions_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_transactions_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_transactions_idempotency_key")),
    )
    op.create_index(
        "ix_transactions_company_occurred",
        "transactions",
        ["company_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_project_occurred",
        "transactions",
        ["project_id", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Append-only tables: the ledger and the FSM audit trail can never be edited or deleted.
    # Corrections are new rows. (Not visible to autogenerate; keep in sync by hand.)
    op.execute(
        """
        CREATE FUNCTION autora_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION autora_forbid_mutation()"
        )


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS autora_forbid_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_project_occurred", table_name="transactions")
    op.drop_index("ix_transactions_company_occurred", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("budgets")
    op.drop_index("ix_state_transitions_entity", table_name="state_transitions")
    op.drop_table("state_transitions")
    op.drop_index(op.f("ix_projects_company_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_table("company_policies")
    op.drop_index(op.f("ix_company_goals_company_id"), table_name="company_goals")
    op.drop_table("company_goals")
    op.drop_table("agents")
    op.drop_table("companies")
    # ### end Alembic commands ###
