"""events outbox and agent activity

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-17 09:23:01.990059+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aggregate_type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("workflow_run_id", sa.UUID(), nullable=True),
        sa.Column("cycle_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column("causation_id", sa.UUID(), nullable=True),
        sa.Column("actor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_events_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("seq", name=op.f("uq_events_seq")),
    )
    op.create_index("ix_events_company_seq", "events", ["company_id", "seq"], unique=False)
    op.create_index("ix_events_correlation_seq", "events", ["correlation_id", "seq"], unique=False)
    op.create_index("ix_events_run_seq", "events", ["run_id", "seq"], unique=False)
    op.create_index("ix_events_task_seq", "events", ["task_id", "seq"], unique=False)
    op.create_index(
        "ix_events_type_occurred", "events", ["event_type", "occurred_at"], unique=False
    )
    op.create_index(
        "ix_events_unprocessed",
        "events",
        ["seq"],
        unique=False,
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.create_table(
        "agent_activity",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_seq", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('IDLE', 'THINKING', 'WORKING', 'WAITING', 'REVIEWING', 'COMPLETED', 'FAILED', 'PAUSED')",
            name=op.f("ck_agent_activity_state_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_agent_activity_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_agent_activity_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("agent_id", name=op.f("pk_agent_activity")),
    )
    op.create_index(
        op.f("ix_agent_activity_company_id"), "agent_activity", ["company_id"], unique=False
    )
    # ### end Alembic commands ###

    # Event log is append-only. The one permitted update is the dispatcher stamping
    # processed_at (NULL -> timestamp); every other column is immutable.
    op.execute(
        """
        CREATE FUNCTION autora_events_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'events is append-only: DELETE is not allowed'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF OLD.processed_at IS NOT NULL
               OR (to_jsonb(NEW) - 'processed_at') IS DISTINCT FROM (to_jsonb(OLD) - 'processed_at')
            THEN
                RAISE EXCEPTION 'events is append-only: only processed_at may be set, once'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER events_append_only BEFORE UPDATE OR DELETE ON events "
        "FOR EACH ROW EXECUTE FUNCTION autora_events_guard()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS events_append_only ON events")
    op.execute("DROP FUNCTION IF EXISTS autora_events_guard()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_activity_company_id"), table_name="agent_activity")
    op.drop_table("agent_activity")
    op.drop_index(
        "ix_events_unprocessed",
        table_name="events",
        postgresql_where=sa.text("processed_at IS NULL"),
    )
    op.drop_index("ix_events_type_occurred", table_name="events")
    op.drop_index("ix_events_task_seq", table_name="events")
    op.drop_index("ix_events_run_seq", table_name="events")
    op.drop_index("ix_events_correlation_seq", table_name="events")
    op.drop_index("ix_events_company_seq", table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
