"""cost reservations

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-17 11:27:19.774403+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_reservations",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_call_id", sa.UUID(), nullable=True),
        sa.Column("actual_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(settled_at IS NULL) = (model_call_id IS NULL)",
            name=op.f("ck_cost_reservations_settled_iff_model_call"),
        ),
        sa.CheckConstraint(
            "NOT (settled_at IS NOT NULL AND released_at IS NOT NULL)",
            name=op.f("ck_cost_reservations_settled_xor_released"),
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_cost_reservations_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_cost_reservations_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["model_call_id"],
            ["model_calls.id"],
            name=op.f("fk_cost_reservations_model_call_id_model_calls"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_cost_reservations_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_cost_reservations_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_cost_reservations_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_reservations")),
    )
    op.create_index(
        "ix_cost_reservations_open",
        "cost_reservations",
        ["company_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("settled_at IS NULL AND released_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_cost_reservations_open",
        table_name="cost_reservations",
        postgresql_where=sa.text("settled_at IS NULL AND released_at IS NULL"),
    )
    op.drop_table("cost_reservations")
    # ### end Alembic commands ###
