"""task claim tokens and retry backoff

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-17 13:13:57.468529+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_agent_runs_open_per_agent",
        "agent_runs",
        ["agent_id"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('COMPLETED', 'FAILED', 'ABORTED')"),
    )
    op.add_column("tasks", sa.Column("available_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("lease_token", sa.UUID(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate does not diff CHECK constraints: a lease now also carries its claim token.
    op.drop_constraint(op.f("ck_tasks_lease_iff_running"), "tasks", type_="check")
    op.create_check_constraint(
        "lease_iff_running",  # naming convention adds the ck_tasks_ prefix
        "tasks",
        "(state = 'RUNNING') = "
        "(lease_owner IS NOT NULL AND lease_until IS NOT NULL AND lease_token IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_tasks_lease_iff_running"), "tasks", type_="check")
    op.create_check_constraint(
        "lease_iff_running",  # naming convention adds the ck_tasks_ prefix
        "tasks",
        "(state = 'RUNNING') = (lease_owner IS NOT NULL AND lease_until IS NOT NULL)",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "lease_token")
    op.drop_column("tasks", "available_at")
    op.drop_index(
        "uq_agent_runs_open_per_agent",
        table_name="agent_runs",
        postgresql_where=sa.text("state NOT IN ('COMPLETED', 'FAILED', 'ABORTED')"),
    )
    # ### end Alembic commands ###
