"""policy decisions

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-18 02:05:36.791939+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_decisions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("actor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("args_hash", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('allow', 'needs_approval', 'deny')",
            name=op.f("ck_policy_decisions_outcome_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agents.id"], name=op.f("fk_policy_decisions_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_policy_decisions_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_policy_decisions_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_policy_decisions_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
    )
    op.create_index(
        "ix_policy_decisions_company_created",
        "policy_decisions",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_policy_decisions_run", "policy_decisions", ["run_id"], unique=False)
    # ### end Alembic commands ###

    # Governance audit trail: append-only (function defined in 0002).
    op.execute(
        "CREATE TRIGGER policy_decisions_append_only BEFORE UPDATE OR DELETE ON policy_decisions "
        "FOR EACH ROW EXECUTE FUNCTION autora_forbid_mutation()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS policy_decisions_append_only ON policy_decisions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_policy_decisions_run", table_name="policy_decisions")
    op.drop_index("ix_policy_decisions_company_created", table_name="policy_decisions")
    op.drop_table("policy_decisions")
    # ### end Alembic commands ###
