"""newsroom sources and source items (T-501)

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-19 06:04:56.029438+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "trust_level", sa.Numeric(precision=3, scale=2), server_default="0.5", nullable=False
        ),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("poll_interval_seconds", sa.Integer(), server_default="3600", nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column(
            "next_poll_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind <> 'rss' OR url IS NOT NULL", name=op.f("ck_sources_rss_has_url")),
        sa.CheckConstraint(
            "kind IN ('rss', 'url_list', 'search_query')", name=op.f("ck_sources_kind_valid")
        ),
        sa.CheckConstraint("status IN ('active', 'paused')", name=op.f("ck_sources_status_valid")),
        sa.CheckConstraint(
            "poll_interval_seconds >= 60", name=op.f("ck_sources_poll_interval_min")
        ),
        sa.CheckConstraint(
            "trust_level >= 0 AND trust_level <= 1", name=op.f("ck_sources_trust_level_range")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_sources_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("company_id", "name", name=op.f("uq_sources_company_id_name")),
    )
    op.create_index(
        "ix_sources_due",
        "sources",
        ["next_poll_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "source_items",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_source_items_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_items_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_items")),
        sa.UniqueConstraint(
            "source_id", "content_hash", name=op.f("uq_source_items_source_id_content_hash")
        ),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_source_items_source_id_external_id")
        ),
    )
    op.create_index(
        "ix_source_items_company_created",
        "source_items",
        ["company_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_source_items_url", "source_items", ["company_id", "url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_source_items_url", table_name="source_items")
    op.drop_index("ix_source_items_company_created", table_name="source_items")
    op.drop_table("source_items")
    op.drop_index(
        "ix_sources_due", table_name="sources", postgresql_where=sa.text("status = 'active'")
    )
    op.drop_table("sources")
    # ### end Alembic commands ###
