"""newsroom evidence chunks (T-503)

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-19 06:42:34.180156+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from autora.db.vector import HalfVector

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_chunks",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("start", sa.Integer(), nullable=False),
        sa.Column("end", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", HalfVector(2048), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_evidence_chunks_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_evidence_chunks_evidence_id_evidence")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_chunks")),
        sa.UniqueConstraint("evidence_id", "seq", name=op.f("uq_evidence_chunks_evidence_id_seq")),
    )
    op.create_index("ix_evidence_chunks_company", "evidence_chunks", ["company_id"], unique=False)
    op.create_index(
        "ix_evidence_chunks_embedding",
        "evidence_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_evidence_chunks_embedding",
        table_name="evidence_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_index("ix_evidence_chunks_company", table_name="evidence_chunks")
    op.drop_table("evidence_chunks")
    # ### end Alembic commands ###
