"""newsroom stories (T-504)

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-19 07:11:56.763668+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from autora.db.vector import HalfVector

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("angle", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), server_default="DISCOVERED", nullable=False),
        sa.Column("score", sa.Numeric(precision=4, scale=3), server_default="0", nullable=False),
        sa.Column("items_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sources_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_item_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("embedding", HalfVector(2048), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=True),
        sa.Column(
            "seed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('DISCOVERED', 'SELECTED', 'IN_PRODUCTION', 'PUBLISHED', 'DROPPED', 'IGNORED')",
            name=op.f("ck_stories_state_valid"),
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_stories_score_range")),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_stories_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_stories_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stories")),
    )
    op.create_index("ix_stories_company_state", "stories", ["company_id", "state"], unique=False)
    op.create_index(
        "ix_stories_embedding",
        "stories",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.create_table(
        "story_items",
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("source_item_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_story_items_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["source_item_id"],
            ["source_items.id"],
            name=op.f("fk_story_items_source_item_id_source_items"),
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["stories.id"], name=op.f("fk_story_items_story_id_stories")
        ),
        sa.PrimaryKeyConstraint("story_id", "source_item_id", name=op.f("pk_story_items")),
        sa.UniqueConstraint("source_item_id", name=op.f("uq_story_items_source_item_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_items")
    op.drop_index(
        "ix_stories_embedding",
        table_name="stories",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "halfvec_cosine_ops"},
    )
    op.drop_index("ix_stories_company_state", table_name="stories")
    op.drop_table("stories")
    # ### end Alembic commands ###
