"""newsroom claims (T-505)

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-19 07:25:55.190437+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "claims",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="UNVERIFIED", nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "claim_type IN ('fact', 'number', 'quote', 'attribution', 'opinion')",
            name=op.f("ck_claims_claim_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('UNVERIFIED', 'VERIFIED', 'REJECTED')", name=op.f("ck_claims_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_claims_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_claims_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["stories.id"], name=op.f("fk_claims_story_id_stories")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_claims_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claims")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_claims_idempotency_key")),
    )
    op.create_index("ix_claims_story", "claims", ["story_id"], unique=False)
    op.create_table(
        "claim_evidence",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("claim_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("quote_start", sa.Integer(), nullable=False),
        sa.Column("quote_end", sa.Integer(), nullable=False),
        sa.Column("support_type", sa.Text(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "support_type IN ('supports', 'contradicts', 'context')",
            name=op.f("ck_claim_evidence_support_type_valid"),
        ),
        sa.CheckConstraint(
            "quote_end > quote_start AND quote_start >= 0",
            name=op.f("ck_claim_evidence_quote_span"),
        ),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["claims.id"], name=op.f("fk_claim_evidence_claim_id_claims")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_claim_evidence_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_claim_evidence_evidence_id_evidence")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_claim_evidence_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_evidence")),
        sa.UniqueConstraint(
            "claim_id",
            "evidence_id",
            "quote_start",
            "support_type",
            name=op.f("uq_claim_evidence_claim_id_evidence_id_quote_start_support_type"),
        ),
    )
    op.create_index("ix_claim_evidence_evidence", "claim_evidence", ["evidence_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_claim_evidence_evidence", table_name="claim_evidence")
    op.drop_table("claim_evidence")
    op.drop_index("ix_claims_story", table_name="claims")
    op.drop_table("claims")
    # ### end Alembic commands ###
