"""newsroom articles (T-508)

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-19 07:53:21.208139+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("primary_lang", sa.Text(), nullable=False),
        sa.Column(
            "published_langs", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("current_draft_group_id", sa.UUID(), nullable=True),
        sa.Column("revision_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'REJECTED')",
            name=op.f("ck_articles_state_valid"),
        ),
        sa.CheckConstraint(
            "revision_count >= 0", name=op.f("ck_articles_revision_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_articles_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["story_id"], ["stories.id"], name=op.f("fk_articles_story_id_stories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("slug", name=op.f("uq_articles_slug")),
        sa.UniqueConstraint("story_id", name=op.f("uq_articles_story_id")),
    )
    op.create_table(
        "article_versions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("draft_group_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("claim_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("translation_of_version_id", sa.UUID(), nullable=True),
        sa.Column("change_summary", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("author_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_article_versions_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["author_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_article_versions_author_run_id_agent_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_article_versions_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_article_versions_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["translation_of_version_id"],
            ["article_versions.id"],
            name=op.f("fk_article_versions_translation_of_version_id_article_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_versions")),
        sa.UniqueConstraint(
            "article_id",
            "version",
            "lang",
            name=op.f("uq_article_versions_article_id_version_lang"),
        ),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_article_versions_idempotency_key")),
    )
    op.create_index(
        "ix_article_versions_group", "article_versions", ["draft_group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_article_versions_group", table_name="article_versions")
    op.drop_table("article_versions")
    op.drop_table("articles")
    # ### end Alembic commands ###
