"""newsroom fact-check reports (T-510)

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-19 08:20:07.884799+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_check_reports",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("article_version_id", sa.UUID(), nullable=False),
        sa.Column("draft_group_id", sa.UUID(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic_review", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_fact_check_reports_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["article_version_id"],
            ["article_versions.id"],
            name=op.f("fk_fact_check_reports_article_version_id_article_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_fact_check_reports_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_fact_check_reports_run_id_agent_runs")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_fact_check_reports_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_check_reports")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_fact_check_reports_idempotency_key")),
    )
    op.create_index(
        "ix_fact_check_reports_article",
        "fact_check_reports",
        ["article_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fact_check_reports_article", table_name="fact_check_reports")
    op.drop_table("fact_check_reports")
    # ### end Alembic commands ###
