"""newsroom distributions (T-512)

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-19 10:40:28.543821+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "distributions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column(
            "copy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_distributions_channel_format")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'failed')", name=op.f("ck_distributions_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_distributions_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_distributions_company_id_companies")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["agent_runs.id"], name=op.f("fk_distributions_run_id_agent_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_distributions")),
    )
    op.create_index("ix_distributions_article", "distributions", ["article_id"], unique=False)
    op.create_index(
        "uq_distributions_site_once",
        "distributions",
        ["article_id"],
        unique=True,
        postgresql_where=sa.text("channel = 'site'"),
    )
    op.add_column("articles", sa.Column("published_group_id", sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "published_group_id")
    op.drop_index(
        "uq_distributions_site_once",
        table_name="distributions",
        postgresql_where=sa.text("channel = 'site'"),
    )
    op.drop_index("ix_distributions_article", table_name="distributions")
    op.drop_table("distributions")
    # ### end Alembic commands ###
