"""newsroom analytics events (T-515)

Revision ID: 0020
Revises: 0019
Create Date: 2026-09-19 14:06:44.568594+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_events",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("session_hash", sa.Text(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('view', 'read_complete')",
            name=op.f("ck_analytics_events_event_type_valid"),
        ),
        sa.CheckConstraint(
            "session_hash ~ '^[0-9a-f]{16,64}$'",
            name=op.f("ck_analytics_events_session_hash_format"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_analytics_events_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_analytics_events_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_events")),
        sa.UniqueConstraint(
            "article_id",
            "lang",
            "event_type",
            "session_hash",
            "day",
            name=op.f("uq_analytics_events_article_id_lang_event_type_session_hash_day"),
        ),
    )
    op.create_index(
        "ix_analytics_events_company_created",
        "analytics_events",
        ["company_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analytics_events_company_created", table_name="analytics_events")
    op.drop_table("analytics_events")
    # ### end Alembic commands ###
