"""newsroom analytics daily (T-516)

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-19 14:19:35.893259+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_daily",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("lang", sa.Text(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("views", sa.Integer(), server_default="0", nullable=False),
        sa.Column("uniques", sa.Integer(), server_default="0", nullable=False),
        sa.Column("read_complete", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "views >= 0 AND uniques >= 0 AND read_complete >= 0",
            name=op.f("ck_analytics_daily_counts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["article_id"], ["articles.id"], name=op.f("fk_analytics_daily_article_id_articles")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_analytics_daily_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_daily")),
        sa.UniqueConstraint(
            "article_id", "lang", "day", name=op.f("uq_analytics_daily_article_id_lang_day")
        ),
    )
    op.create_index(
        "ix_analytics_daily_company_day", "analytics_daily", ["company_id", "day"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analytics_daily_company_day", table_name="analytics_daily")
    op.drop_table("analytics_daily")
    # ### end Alembic commands ###
