/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analytics/beacon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Beacon
         * @description Count a view or a completed read. A repeat from the same session that day is dropped
         *     (still 204: the reader's page has nothing to do about it).
         */
        post: operations["beacon_api_analytics_beacon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description The approval inbox. Oldest first, so the longest-waiting request is on top.
         */
        get: operations["list_approvals_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_approvals__approval_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{article_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_articles__article_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /** Post Company */
        post: operations["post_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Company Agents */
        get: operations["list_company_agents_api_companies__company_id__agents_get"];
        put?: never;
        /**
         * Hire
         * @description Hire an agent: it appears in the office and starts taking its role's tasks.
         */
        post: operations["hire_api_companies__company_id__agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/agents/{agent_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause
         * @description No new tasks for this agent; the run it is on still finishes.
         */
        post: operations["pause_api_companies__company_id__agents__agent_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/agents/{agent_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_companies__company_id__agents__agent_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/agents/{agent_id}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retire
         * @description The agent leaves the roster. Its runs, events and outputs stay; it cannot be brought back.
         */
        post: operations["retire_api_companies__company_id__agents__agent_id__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_companies__company_id__articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kpis
         * @description Cash, today's revenue and expenses (model calls included), today's goal.
         */
        get: operations["get_kpis_api_companies__company_id__kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/realtime/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description Agents, active tasks, recent events and ``last_seq``, read at one consistent moment.
         *     Connect the WebSocket with ``since=last_seq`` and apply newer events on top.
         */
        get: operations["get_snapshot_api_companies__company_id__realtime_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_companies__company_id__sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_companies__company_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stories */
        get: operations["list_stories_api_companies__company_id__stories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Workflow */
        post: operations["post_workflow_api_companies__company_id__workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Events of one company ordered by ``seq``. Used for trace views and realtime gap-fill.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Articles */
        get: operations["list_articles_api_public_articles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/articles/{lang}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Article */
        get: operations["get_article_api_public_articles__lang___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Roles */
        get: operations["list_roles_api_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps/{seq}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step Blob
         * @description Full prompt/response payload of one step (admin only).
         */
        get: operations["step_blob_api_runs__run_id__steps__seq__blob_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trace
         * @description The run's real events in seq order, each joined with the agent step it belongs to.
         */
        get: operations["run_trace_api_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story */
        get: operations["get_story_api_stories__story_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stories/{story_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Select the story (if it was only discovered) and start its workflow.
         */
        post: operations["start_api_stories__story_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOut */
        ActivityOut: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** State */
            state: string;
            /** Stored State */
            stored_state: string;
            /** Task Id */
            task_id: string | null;
        };
        /**
         * ActivityState
         * @enum {string}
         */
        ActivityState: "IDLE" | "THINKING" | "WORKING" | "WAITING" | "REVIEWING" | "COMPLETED" | "FAILED" | "PAUSED";
        /** ActivityView */
        ActivityView: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            state: components["schemas"]["ActivityState"];
            stored_state: components["schemas"]["ActivityState"];
            /** Task Id */
            task_id: string | null;
        };
        /** Actor */
        Actor: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "system" | "human";
        };
        /** AgentDecision */
        AgentDecision: {
            /** Reason */
            reason?: string | null;
        };
        /** AgentOut */
        AgentOut: {
            activity: components["schemas"]["ActivityOut"] | null;
            /** Avatar Key */
            avatar_key: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** AgentView */
        AgentView: {
            activity: components["schemas"]["ActivityView"];
            /** Avatar Key */
            avatar_key: string;
            /** Department Id */
            department_id?: string | null;
            /** Department Key */
            department_key?: string | null;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
        };
        /**
         * AnalyticsEventType
         * @enum {string}
         */
        AnalyticsEventType: "view" | "read_complete";
        /** ApprovalOut */
        ApprovalOut: {
            /** Action */
            action: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: {
                [key: string]: unknown;
            } | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string | null;
            /**
             * Ref Id
             * Format: uuid
             */
            ref_id: string;
            /** Ref Type */
            ref_type: string;
            /** Requested By */
            requested_by: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string | null;
            /** State */
            state: string;
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /**
         * ApprovalState
         * @enum {string}
         */
        ApprovalState: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED";
        /** ArticleDetail */
        ArticleDetail: {
            /** Analytics */
            analytics: components["schemas"]["DailyView"][];
            /** Claims */
            claims: components["schemas"]["ClaimView"][];
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Distributions */
            distributions: components["schemas"]["DistributionView"][];
            /** Fact Checks */
            fact_checks: components["schemas"]["FactCheckView"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Langs */
            langs: string[];
            /** Languages */
            languages: {
                [key: string]: components["schemas"]["LanguageView"];
            };
            /** Primary Lang */
            primary_lang: string;
            /** Public Urls */
            public_urls: {
                [key: string]: string;
            };
            /** Published At */
            published_at: string | null;
            /** Published Langs */
            published_langs: string[];
            /** Revision Count */
            revision_count: number;
            /** Shown */
            shown: number | null;
            /** Slug */
            slug: string;
            /** State */
            state: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Story Title */
            story_title: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number | null;
            /** Versions */
            versions: components["schemas"]["VersionView"][];
            /** Views */
            views: number;
            /** Workflow Run Ids */
            workflow_run_ids: string[];
        };
        /** ArticleRef */
        ArticleRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** ArticleSummary */
        ArticleSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Langs */
            langs: string[];
            /** Published At */
            published_at: string | null;
            /** Revision Count */
            revision_count: number;
            /** Slug */
            slug: string;
            /** State */
            state: string;
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number | null;
            /** Views */
            views: number;
        };
        /** Beacon */
        Beacon: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            event_type: components["schemas"]["AnalyticsEventType"];
            /** Lang */
            lang: string;
            /**
             * Session Hash
             * @description A random id the reader's browser makes each day; nothing about the reader.
             */
            session_hash: string;
        };
        /** BlockView */
        BlockView: {
            /** Claim Ids */
            claim_ids: string[];
            /** Text */
            text: string;
            /** Type */
            type: string;
        };
        /** ClaimView */
        ClaimView: {
            /** Claim Type */
            claim_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Quotes */
            quotes: components["schemas"]["QuoteView"][];
            /** Status */
            status: string;
            /** Text */
            text: string;
        };
        /** CompanyCreate */
        CompanyCreate: {
            /** Mission */
            mission?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            type: components["schemas"]["CompanyType"];
        };
        /** CompanyOut */
        CompanyOut: {
            /**
             * Agents
             * @default 0
             */
            agents: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mission */
            mission: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * CompanyType
         * @enum {string}
         */
        CompanyType: "newsroom" | "saas" | "research" | "ecommerce" | "software_studio";
        /** DailyView */
        DailyView: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Lang */
            lang: string;
            /** Read Complete */
            read_complete: number;
            /** Uniques */
            uniques: number;
            /** Views */
            views: number;
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason?: string | null;
        };
        /** DistributionView */
        DistributionView: {
            /** Channel */
            channel: string;
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** External Ref */
            external_ref: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** EventEnvelope */
        EventEnvelope: {
            actor: components["schemas"]["Actor"];
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Aggregate Type */
            aggregate_type: string;
            /** Causation Id */
            causation_id?: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Cycle Id */
            cycle_id?: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["EventPayload"];
            /** Run Id */
            run_id?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Seq */
            seq?: number | null;
            /** Task Id */
            task_id?: string | null;
            /** Workflow Run Id */
            workflow_run_id?: string | null;
        };
        /**
         * EventPayload
         * @description Base class for typed payloads. Subclasses are registered with ``@event``.
         */
        EventPayload: Record<string, never>;
        /** EventsPage */
        EventsPage: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Next After */
            next_after: number;
        };
        /** EvidenceView */
        EvidenceView: {
            /** Chars */
            chars: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Run Id */
            run_id: string | null;
            /** Site */
            site: string;
            /** Title */
            title: string | null;
            /** Truncated */
            truncated: boolean;
            /** Trust Level */
            trust_level: string | null;
            /** Url */
            url: string;
        };
        /** FactCheckView */
        FactCheckView: {
            /** Checked */
            checked: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Failed */
            failed: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Passed */
            passed: boolean;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Version */
            version: number | null;
        };
        /** GoalView */
        GoalView: {
            /** Current */
            current: string | null;
            /** Deadline */
            deadline: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metric */
            metric: string;
            /** Target */
            target: string;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Kpis */
        Kpis: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Cash */
            cash: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Expenses Today */
            expenses_today: string;
            goal?: components["schemas"]["GoalView"] | null;
            /** Model Cost Today */
            model_cost_today: string;
            /** Published Today */
            published_today?: number | null;
            /** Revenue Today */
            revenue_today: string;
        };
        /** LanguageView */
        LanguageView: {
            /** Blocks */
            blocks: components["schemas"]["BlockView"][];
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
        };
        /** Lead */
        Lead: {
            /** Published At */
            published_at: string | null;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** NewAgent */
        NewAgent: {
            /**
             * Avatar Key
             * @default default
             */
            avatar_key: string;
            /** Description */
            description?: string | null;
            /** Display Name */
            display_name: string;
            /** Per Run Usd */
            per_run_usd?: number | string | null;
            /** Role */
            role: string;
            /**
             * Tools
             * @default []
             */
            tools: string[];
        };
        /** NewSource */
        NewSource: {
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: unknown;
            };
            kind: components["schemas"]["SourceKind"];
            /** Language */
            language?: string | null;
            /** Name */
            name: string;
            /**
             * Poll Interval Seconds
             * @default 3600
             */
            poll_interval_seconds: number;
            /**
             * Trust Level
             * @default 0.5
             */
            trust_level: number | string;
            /** Url */
            url?: string | null;
        };
        /** PublicArticle */
        PublicArticle: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Blocks */
            blocks: components["schemas"]["PublicBlock"][];
            /** Company */
            company: string;
            /** Lang */
            lang: string;
            /** Langs */
            langs: {
                [key: string]: string;
            };
            /** Path */
            path: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Slug */
            slug: string;
            /** Sources */
            sources: components["schemas"]["PublicSource"][];
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** PublicArticleSummary */
        PublicArticleSummary: {
            /**
             * Article Id
             * Format: uuid
             */
            article_id: string;
            /** Lang */
            lang: string;
            /** Path */
            path: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Slug */
            slug: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** PublicBlock */
        PublicBlock: {
            /** Text */
            text: string;
            /** Type */
            type: string;
        };
        /** PublicSource */
        PublicSource: {
            /** Site */
            site: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** QuoteView */
        QuoteView: {
            /** After */
            after: string;
            /** Before */
            before: string;
            /**
             * Evidence Id
             * Format: uuid
             */
            evidence_id: string;
            /** Evidence Title */
            evidence_title: string | null;
            /** Quote */
            quote: string;
            /** Support Type */
            support_type: string;
            /** Url */
            url: string;
        };
        /** RealtimeSnapshot */
        RealtimeSnapshot: {
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cycle */
            cycle?: {
                [key: string]: unknown;
            } | null;
            /** Kpis */
            kpis?: {
                [key: string]: unknown;
            } | null;
            /** Last Seq */
            last_seq: number;
            /** Recent Events */
            recent_events: components["schemas"]["EventEnvelope"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Tasks */
            tasks: components["schemas"]["TaskView"][];
        };
        /** Roles */
        Roles: {
            /** Roles */
            roles: string[];
        };
        /**
         * RunOut
         * @description One agent run: what it was asked, what it produced, what it cost.
         */
        RunOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cost Usd */
            cost_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Evaluation */
            evaluation: {
                [key: string]: unknown;
            } | null;
            /** Finished At */
            finished_at: string | null;
            /** Handoff */
            handoff: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
            /** Steps Count */
            steps_count: number;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /**
         * SourceKind
         * @enum {string}
         */
        SourceKind: "rss" | "url_list" | "search_query";
        /** SourceView */
        SourceView: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: number;
            /** Kind */
            kind: string;
            /** Language */
            language: string | null;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Name */
            name: string;
            /**
             * Next Poll At
             * Format: date-time
             */
            next_poll_at: string;
            /** Poll Interval Seconds */
            poll_interval_seconds: number;
            /** Status */
            status: string;
            /** Trust Level */
            trust_level: string;
            /** Url */
            url: string | null;
        };
        /** StartStory */
        StartStory: {
            /**
             * Project Id
             * @description Default: the story's project, else the first active one.
             */
            project_id?: string | null;
        };
        /** StartedStory */
        StartedStory: {
            /**
             * Story Id
             * Format: uuid
             */
            story_id: string;
            /**
             * Workflow Run Id
             * Format: uuid
             */
            workflow_run_id: string;
        };
        /** StepView */
        StepView: {
            /** Cost Usd */
            cost_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Blob */
            has_blob: boolean;
            /** Kind */
            kind: string;
            /** Seq */
            seq: number;
            /** Summary */
            summary: string | null;
            /** Tool Calls */
            tool_calls: {
                [key: string]: unknown;
            }[] | null;
        };
        /** StoryDetail */
        StoryDetail: {
            /** Angle */
            angle: string | null;
            article: components["schemas"]["ArticleRef"] | null;
            /** Claim List */
            claim_list: components["schemas"]["ClaimView"][];
            /** Claims */
            claims: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Evidence */
            evidence: number;
            /** Evidence List */
            evidence_list: components["schemas"]["EvidenceView"][];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: number;
            /** Leads */
            leads: components["schemas"]["Lead"][];
            /** Score */
            score: string;
            /** Seed */
            seed: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: number;
            /** State */
            state: string;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
            /** Workflow Run Ids */
            workflow_run_ids: string[];
        };
        /**
         * StoryState
         * @description platform/02 §6: DISCOVERED -> SELECTED -> IN_PRODUCTION -> PUBLISHED | DROPPED;
         *     DISCOVERED -> IGNORED.
         * @enum {string}
         */
        StoryState: "DISCOVERED" | "SELECTED" | "IN_PRODUCTION" | "PUBLISHED" | "DROPPED" | "IGNORED";
        /** StorySummary */
        StorySummary: {
            article: components["schemas"]["ArticleRef"] | null;
            /** Claims */
            claims: number;
            /** Evidence */
            evidence: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: number;
            /** Score */
            score: string;
            /** Sources */
            sources: number;
            /** State */
            state: string;
            /** Title */
            title: string;
        };
        /** TaskDetailOut */
        TaskDetailOut: {
            /** Attempt */
            attempt: number;
            /** Budget Usd */
            budget_usd: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Max Attempts */
            max_attempts: number;
            /** Name */
            name: string;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Priority */
            priority: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Required Role */
            required_role: string;
            /** Runs */
            runs: components["schemas"]["TaskRunOut"][];
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workflow Run Id */
            workflow_run_id: string | null;
        };
        /** TaskRunOut */
        TaskRunOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /** Cost Usd */
            cost_usd: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
        };
        /** TaskView */
        TaskView: {
            /** Agent Id */
            agent_id: string | null;
            /** Attempt */
            attempt: number;
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Event Seq */
            last_event_seq: number;
            /** Name */
            name: string;
            /** Required Role */
            required_role: string;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** State */
            state: string;
            /** Workflow Run Id */
            workflow_run_id: string | null;
        };
        /** Trace */
        Trace: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cost Usd */
            cost_usd: string;
            /** Entries */
            entries: components["schemas"]["TraceEntry"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** State */
            state: string;
            /** Steps */
            steps: components["schemas"]["StepView"][];
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** TraceEntry */
        TraceEntry: {
            /** Actor */
            actor: {
                [key: string]: unknown;
            };
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Seq */
            seq: number;
            step: components["schemas"]["StepView"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionView */
        VersionView: {
            /** Change Summary */
            change_summary: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current */
            current: boolean;
            /**
             * Draft Group Id
             * Format: uuid
             */
            draft_group_id: string;
            /** Langs */
            langs: string[];
            /** Published */
            published: boolean;
            /** Version */
            version: number;
        };
        /** WorkflowRunOut */
        WorkflowRunOut: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** State */
            state: string;
            /** Tasks */
            tasks: components["schemas"]["WorkflowTaskOut"][];
            /** Template Name */
            template_name: string;
        };
        /** WorkflowStart */
        WorkflowStart: {
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Template */
            template: string;
        };
        /** WorkflowTaskOut */
        WorkflowTaskOut: {
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Required Role */
            required_role: string;
            /** State */
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    beacon_api_analytics_beacon_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Beacon"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvals_api_approvals_get: {
        parameters: {
            query: {
                company_id: string;
                state?: components["schemas"]["ApprovalState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_approvals__approval_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_articles__article_id__get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                article_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: {
                /** @description Archived companies too */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_agents_api_companies__company_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hire_api_companies__company_id__agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAgent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_api_companies__company_id__agents__agent_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_companies__company_id__agents__agent_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_api_companies__company_id__agents__agent_id__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_companies__company_id__articles_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kpis_api_companies__company_id__kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kpis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_companies__company_id__realtime_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_companies__company_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_api_companies__company_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewSource"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stories_api_companies__company_id__stories_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["StoryState"] | null;
                limit?: number;
            };
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_workflow_api_companies__company_id__workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query: {
                company_id: string;
                /** @description Return events with seq > after */
                after?: number;
                /** @description Return events with seq <= until */
                until?: number | null;
                /** @description Filter by event_type (repeatable) */
                type?: string[] | null;
                agent_id?: string | null;
                run_id?: string | null;
                /** @description One workflow run's story: its events carry its id as correlation */
                correlation_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_articles_api_public_articles_get: {
        parameters: {
            query: {
                lang: string;
                company?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicArticleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_article_api_public_articles__lang___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lang: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicArticle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roles_api_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roles"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_blob_api_runs__run_id__steps__seq__blob_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trace_api_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_api_stories__story_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_stories__story_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                story_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartStory"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartedStory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
