/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approvals
         * @description The approval inbox. Oldest first, so the longest-waiting request is on top.
         */
        get: operations["list_approvals_api_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/approvals/{approval_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_approvals__approval_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /** Post Company */
        post: operations["post_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Company Agents */
        get: operations["list_company_agents_api_companies__company_id__agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/realtime/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshot
         * @description Agents, active tasks, recent events and ``last_seq``, read at one consistent moment.
         *     Connect the WebSocket with ``since=last_seq`` and apply newer events on top.
         */
        get: operations["get_snapshot_api_companies__company_id__realtime_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Workflow */
        post: operations["post_workflow_api_companies__company_id__workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Events of one company ordered by ``seq``. Used for trace views and realtime gap-fill.
         */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps/{seq}/blob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Step Blob
         * @description Full prompt/response payload of one step (admin only).
         */
        get: operations["step_blob_api_runs__run_id__steps__seq__blob_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Trace
         * @description The run's real events in seq order, each joined with the agent step it belongs to.
         */
        get: operations["run_trace_api_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityOut */
        ActivityOut: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** State */
            state: string;
            /** Stored State */
            stored_state: string;
            /** Task Id */
            task_id: string | null;
        };
        /**
         * ActivityState
         * @enum {string}
         */
        ActivityState: "IDLE" | "THINKING" | "WORKING" | "WAITING" | "REVIEWING" | "COMPLETED" | "FAILED" | "PAUSED";
        /** ActivityView */
        ActivityView: {
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Last Event Seq */
            last_event_seq: number;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            state: components["schemas"]["ActivityState"];
            stored_state: components["schemas"]["ActivityState"];
            /** Task Id */
            task_id: string | null;
        };
        /** Actor */
        Actor: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "system" | "human";
        };
        /** AgentOut */
        AgentOut: {
            activity: components["schemas"]["ActivityOut"] | null;
            /** Avatar Key */
            avatar_key: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** AgentView */
        AgentView: {
            activity: components["schemas"]["ActivityView"];
            /** Avatar Key */
            avatar_key: string;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
        };
        /** ApprovalOut */
        ApprovalOut: {
            /** Action */
            action: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: {
                [key: string]: unknown;
            } | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string | null;
            /**
             * Ref Id
             * Format: uuid
             */
            ref_id: string;
            /** Ref Type */
            ref_type: string;
            /** Requested By */
            requested_by: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string | null;
            /** State */
            state: string;
            /** Summary */
            summary: string;
            /** Task Id */
            task_id: string | null;
        };
        /**
         * ApprovalState
         * @enum {string}
         */
        ApprovalState: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED";
        /** CompanyCreate */
        CompanyCreate: {
            /** Mission */
            mission?: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            type: components["schemas"]["CompanyType"];
        };
        /** CompanyOut */
        CompanyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mission */
            mission: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Type */
            type: string;
        };
        /**
         * CompanyType
         * @enum {string}
         */
        CompanyType: "newsroom" | "saas" | "research" | "ecommerce" | "software_studio";
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "reject";
            /** Reason */
            reason?: string | null;
        };
        /** EventEnvelope */
        EventEnvelope: {
            actor: components["schemas"]["Actor"];
            /** Agent Id */
            agent_id?: string | null;
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Aggregate Type */
            aggregate_type: string;
            /** Causation Id */
            causation_id?: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Cycle Id */
            cycle_id?: string | null;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            payload: components["schemas"]["EventPayload"];
            /** Run Id */
            run_id?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Seq */
            seq?: number | null;
            /** Task Id */
            task_id?: string | null;
            /** Workflow Run Id */
            workflow_run_id?: string | null;
        };
        /**
         * EventPayload
         * @description Base class for typed payloads. Subclasses are registered with ``@event``.
         */
        EventPayload: Record<string, never>;
        /** EventsPage */
        EventsPage: {
            /** Has More */
            has_more: boolean;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Next After */
            next_after: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RealtimeSnapshot */
        RealtimeSnapshot: {
            /** Agents */
            agents: components["schemas"]["AgentView"][];
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cycle */
            cycle?: {
                [key: string]: unknown;
            } | null;
            /** Kpis */
            kpis?: {
                [key: string]: unknown;
            } | null;
            /** Last Seq */
            last_seq: number;
            /** Recent Events */
            recent_events: components["schemas"]["EventEnvelope"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /** Tasks */
            tasks: components["schemas"]["TaskView"][];
        };
        /**
         * RunOut
         * @description One agent run: what it was asked, what it produced, what it cost.
         */
        RunOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cost Usd */
            cost_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
            /** Evaluation */
            evaluation: {
                [key: string]: unknown;
            } | null;
            /** Finished At */
            finished_at: string | null;
            /** Handoff */
            handoff: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
            /** Steps Count */
            steps_count: number;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** StepView */
        StepView: {
            /** Cost Usd */
            cost_usd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Has Blob */
            has_blob: boolean;
            /** Kind */
            kind: string;
            /** Seq */
            seq: number;
            /** Summary */
            summary: string | null;
            /** Tool Calls */
            tool_calls: {
                [key: string]: unknown;
            }[] | null;
        };
        /** TaskRunOut */
        TaskRunOut: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /** Cost Usd */
            cost_usd: string;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** State */
            state: string;
        };
        /** TaskView */
        TaskView: {
            /** Agent Id */
            agent_id: string | null;
            /** Attempt */
            attempt: number;
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Event Seq */
            last_event_seq: number;
            /** Name */
            name: string;
            /** Required Role */
            required_role: string;
            /** Run Id */
            run_id: string | null;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /** State */
            state: string;
            /** Workflow Run Id */
            workflow_run_id: string | null;
        };
        /** Trace */
        Trace: {
            /**
             * Agent Id
             * Format: uuid
             */
            agent_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Cost Usd */
            cost_usd: string;
            /** Entries */
            entries: components["schemas"]["TraceEntry"][];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** State */
            state: string;
            /** Steps */
            steps: components["schemas"]["StepView"][];
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
        };
        /** TraceEntry */
        TraceEntry: {
            /** Actor */
            actor: {
                [key: string]: unknown;
            };
            /** Event Type */
            event_type: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Seq */
            seq: number;
            step: components["schemas"]["StepView"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkflowRunOut */
        WorkflowRunOut: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** State */
            state: string;
            /** Tasks */
            tasks: components["schemas"]["autora_api__routers__workflows__TaskOut"][];
            /** Template Name */
            template_name: string;
        };
        /** WorkflowStart */
        WorkflowStart: {
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Template */
            template: string;
        };
        /** TaskOut */
        autora_api__routers__tasks__TaskOut: {
            /** Attempt */
            attempt: number;
            /** Budget Usd */
            budget_usd: string | null;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input */
            input: {
                [key: string]: unknown;
            };
            /** Max Attempts */
            max_attempts: number;
            /** Name */
            name: string;
            /** Output */
            output: {
                [key: string]: unknown;
            } | null;
            /** Priority */
            priority: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Required Role */
            required_role: string;
            /** Runs */
            runs: components["schemas"]["TaskRunOut"][];
            /** State */
            state: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workflow Run Id */
            workflow_run_id: string | null;
        };
        /** TaskOut */
        autora_api__routers__workflows__TaskOut: {
            /** Depends On */
            depends_on: string[];
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Required Role */
            required_role: string;
            /** State */
            state: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approvals_api_approvals_get: {
        parameters: {
            query: {
                company_id: string;
                state?: components["schemas"]["ApprovalState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_approvals__approval_id__decide_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
        };
    };
    post_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_company_agents_api_companies__company_id__agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshot_api_companies__company_id__realtime_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_workflow_api_companies__company_id__workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query: {
                company_id: string;
                /** @description Return events with seq > after */
                after?: number;
                /** @description Return events with seq <= until */
                until?: number | null;
                /** @description Filter by event_type (repeatable) */
                type?: string[] | null;
                agent_id?: string | null;
                run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    step_blob_api_runs__run_id__steps__seq__blob_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trace_api_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["autora_api__routers__tasks__TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
