// GENERATED by `make gen-schema` from autora.runtime.events (pydantic). Do not edit.
// Source of truth: backend/autora/**/events.py

import { z } from "zod";

// --- shared models ----------------------------------------------------------------------

export const Actor = z.object({
  kind: z.enum(["agent", "system", "human"]),
  id: z.string().min(1),
});
export type Actor = z.infer<typeof Actor>;

export const Handoff = z.object({
  to_role: z.string(),
  task_id: z.uuid(),
});
export type Handoff = z.infer<typeof Handoff>;

export const ProducedRef = z.object({
  type: z.string(),
  id: z.uuid(),
});
export type ProducedRef = z.infer<typeof ProducedRef>;

export const Progress = z.object({
  label: z.string(),
  current: z.number().int().min(0),
  target: z.number().int().min(0).nullable().default(null),
});
export type Progress = z.infer<typeof Progress>;

export const UnlockedTask = z.object({
  task_id: z.uuid(),
  required_role: z.string(),
});
export type UnlockedTask = z.infer<typeof UnlockedTask>;

// --- envelope ---------------------------------------------------------------------------

const envelopeFields = {
  event_id: z.uuid(),
  seq: z.number().int().nullable().default(null),
  company_id: z.uuid(),
  occurred_at: z.iso.datetime({ offset: true }),
  aggregate_type: z.string(),
  aggregate_id: z.uuid(),
  agent_id: z.uuid().nullable().default(null),
  task_id: z.uuid().nullable().default(null),
  run_id: z.uuid().nullable().default(null),
  workflow_run_id: z.uuid().nullable().default(null),
  cycle_id: z.uuid().nullable().default(null),
  correlation_id: z.uuid().nullable().default(null),
  causation_id: z.uuid().nullable().default(null),
  actor: Actor,
};

// --- events -----------------------------------------------------------------------------

export const AgentCreatedV1Payload = z.object({
  role: z.string(),
  display_name: z.string(),
  capabilities: z.array(z.string()).default(() => ([])),
  avatar_key: z.string().default("default"),
});
export type AgentCreatedV1Payload = z.infer<typeof AgentCreatedV1Payload>;
export const AgentCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_CREATED"),
  schema_version: z.literal(1),
  payload: AgentCreatedV1Payload,
});

export const AgentHeartbeatV1Payload = z.object({
  alive_at: z.iso.datetime({ offset: true }),
});
export type AgentHeartbeatV1Payload = z.infer<typeof AgentHeartbeatV1Payload>;
export const AgentHeartbeatV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_HEARTBEAT"),
  schema_version: z.literal(1),
  payload: AgentHeartbeatV1Payload,
});

export const AgentIdleV1Payload = z.object({
  reason: z.enum(["failure_acknowledged", "waiting_cleared", "initialized", "run_ended"]),
});
export type AgentIdleV1Payload = z.infer<typeof AgentIdleV1Payload>;
export const AgentIdleV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_IDLE"),
  schema_version: z.literal(1),
  payload: AgentIdleV1Payload,
});

export const AgentPausedV1Payload = z.object({
  reason: z.string().nullable().default(null),
});
export type AgentPausedV1Payload = z.infer<typeof AgentPausedV1Payload>;
export const AgentPausedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_PAUSED"),
  schema_version: z.literal(1),
  payload: AgentPausedV1Payload,
});

export const AgentResumedV1Payload = z.object({
  reason: z.string().nullable().default(null),
});
export type AgentResumedV1Payload = z.infer<typeof AgentResumedV1Payload>;
export const AgentResumedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_RESUMED"),
  schema_version: z.literal(1),
  payload: AgentResumedV1Payload,
});

export const AgentReviewingV1Payload = z.object({
  phase: z.enum(["evaluate", "repair"]),
  attempt: z.number().int().min(1),
  issues_count: z.number().int().min(0),
});
export type AgentReviewingV1Payload = z.infer<typeof AgentReviewingV1Payload>;
export const AgentReviewingV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_REVIEWING"),
  schema_version: z.literal(1),
  payload: AgentReviewingV1Payload,
});

export const AgentRunAbortedV1Payload = z.object({
  reason: z.enum(["budget", "policy", "timeout", "human"]),
  message: z.string().nullable().default(null),
  final: z.boolean().default(true),
});
export type AgentRunAbortedV1Payload = z.infer<typeof AgentRunAbortedV1Payload>;
export const AgentRunAbortedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_RUN_ABORTED"),
  schema_version: z.literal(1),
  payload: AgentRunAbortedV1Payload,
});

export const AgentRunCompletedV1Payload = z.object({
  output_summary: z.string().nullable().default(null),
  cost_usd: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  steps: z.number().int().min(0),
  duration_ms: z.number().int().min(0),
  handoff: z.array(Handoff).default(() => ([])),
  display_until: z.iso.datetime({ offset: true }).nullable().default(null),
});
export type AgentRunCompletedV1Payload = z.infer<typeof AgentRunCompletedV1Payload>;
export const AgentRunCompletedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_RUN_COMPLETED"),
  schema_version: z.literal(1),
  payload: AgentRunCompletedV1Payload,
});

export const AgentRunFailedV1Payload = z.object({
  error_class: z.string(),
  message: z.string(),
  attempt: z.number().int().min(1),
  final: z.boolean(),
});
export type AgentRunFailedV1Payload = z.infer<typeof AgentRunFailedV1Payload>;
export const AgentRunFailedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_RUN_FAILED"),
  schema_version: z.literal(1),
  payload: AgentRunFailedV1Payload,
});

export const AgentRunStartedV1Payload = z.object({
  attempt: z.number().int().min(1),
  task_name: z.string(),
  required_role: z.string(),
  input_summary: z.string().nullable().default(null),
});
export type AgentRunStartedV1Payload = z.infer<typeof AgentRunStartedV1Payload>;
export const AgentRunStartedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_RUN_STARTED"),
  schema_version: z.literal(1),
  payload: AgentRunStartedV1Payload,
});

export const AgentStepProgressV1Payload = z.object({
  step_seq: z.number().int().min(0),
  tokens_so_far: z.number().int().min(0),
  progress: Progress.nullable().default(null),
});
export type AgentStepProgressV1Payload = z.infer<typeof AgentStepProgressV1Payload>;
export const AgentStepProgressV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_STEP_PROGRESS"),
  schema_version: z.literal(1),
  payload: AgentStepProgressV1Payload,
});

export const AgentThinkingV1Payload = z.object({
  phase: z.enum(["plan", "reason", "finalize"]),
  step_seq: z.number().int().min(0),
});
export type AgentThinkingV1Payload = z.infer<typeof AgentThinkingV1Payload>;
export const AgentThinkingV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_THINKING"),
  schema_version: z.literal(1),
  payload: AgentThinkingV1Payload,
});

export const AgentWaitingV1Payload = z.object({
  reason: z.enum(["approval", "budget", "upstream", "rate_limit"]),
  approval_id: z.uuid().nullable().default(null),
  blocked_task_id: z.uuid().nullable().default(null),
  waiting_on_roles: z.array(z.string()).default(() => ([])),
});
export type AgentWaitingV1Payload = z.infer<typeof AgentWaitingV1Payload>;
export const AgentWaitingV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_WAITING"),
  schema_version: z.literal(1),
  payload: AgentWaitingV1Payload,
});

export const AgentWorkingV1Payload = z.object({
  tool: z.string(),
  tool_call_id: z.string(),
  step_seq: z.number().int().min(0),
  progress: Progress.nullable().default(null),
});
export type AgentWorkingV1Payload = z.infer<typeof AgentWorkingV1Payload>;
export const AgentWorkingV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("AGENT_WORKING"),
  schema_version: z.literal(1),
  payload: AgentWorkingV1Payload,
});

export const ApprovalApprovedV1Payload = z.object({
  kind: z.enum(["tool_call", "command", "project", "kill", "strategy", "article"]),
  ref_type: z.string(),
  ref_id: z.uuid(),
  reason: z.string().nullable().default(null),
});
export type ApprovalApprovedV1Payload = z.infer<typeof ApprovalApprovedV1Payload>;
export const ApprovalApprovedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("APPROVAL_APPROVED"),
  schema_version: z.literal(1),
  payload: ApprovalApprovedV1Payload,
});

export const ApprovalExpiredV1Payload = z.object({
  kind: z.enum(["tool_call", "command", "project", "kill", "strategy", "article"]),
  ref_type: z.string(),
  ref_id: z.uuid(),
});
export type ApprovalExpiredV1Payload = z.infer<typeof ApprovalExpiredV1Payload>;
export const ApprovalExpiredV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("APPROVAL_EXPIRED"),
  schema_version: z.literal(1),
  payload: ApprovalExpiredV1Payload,
});

export const ApprovalRejectedV1Payload = z.object({
  kind: z.enum(["tool_call", "command", "project", "kill", "strategy", "article"]),
  ref_type: z.string(),
  ref_id: z.uuid(),
  reason: z.string().nullable().default(null),
});
export type ApprovalRejectedV1Payload = z.infer<typeof ApprovalRejectedV1Payload>;
export const ApprovalRejectedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("APPROVAL_REJECTED"),
  schema_version: z.literal(1),
  payload: ApprovalRejectedV1Payload,
});

export const ApprovalRequestedV1Payload = z.object({
  kind: z.enum(["tool_call", "command", "project", "kill", "strategy", "article"]),
  ref_type: z.string(),
  ref_id: z.uuid(),
  summary: z.string(),
  expires_at: z.iso.datetime({ offset: true }).nullable().default(null),
});
export type ApprovalRequestedV1Payload = z.infer<typeof ApprovalRequestedV1Payload>;
export const ApprovalRequestedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("APPROVAL_REQUESTED"),
  schema_version: z.literal(1),
  payload: ApprovalRequestedV1Payload,
});

export const BudgetAllocatedV1Payload = z.object({
  budget_id: z.uuid(),
  project_id: z.uuid().nullable().default(null),
  period: z.enum(["cycle", "day", "month"]),
  amount: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  currency: z.string().default("USD"),
});
export type BudgetAllocatedV1Payload = z.infer<typeof BudgetAllocatedV1Payload>;
export const BudgetAllocatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("BUDGET_ALLOCATED"),
  schema_version: z.literal(1),
  payload: BudgetAllocatedV1Payload,
});

export const BudgetExhaustedV1Payload = z.object({
  scope: z.enum(["company", "project", "task", "run"]),
  project_id: z.uuid().nullable().default(null),
  task_id: z.uuid().nullable().default(null),
  limit: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  spent: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  requested: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).default("0"),
  currency: z.string().default("USD"),
});
export type BudgetExhaustedV1Payload = z.infer<typeof BudgetExhaustedV1Payload>;
export const BudgetExhaustedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("BUDGET_EXHAUSTED"),
  schema_version: z.literal(1),
  payload: BudgetExhaustedV1Payload,
});

export const CompanyCreatedV1Payload = z.object({
  slug: z.string(),
  name: z.string(),
  type: z.string(),
});
export type CompanyCreatedV1Payload = z.infer<typeof CompanyCreatedV1Payload>;
export const CompanyCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("COMPANY_CREATED"),
  schema_version: z.literal(1),
  payload: CompanyCreatedV1Payload,
});

export const CycleCompletedV1Payload = z.object({
  seq: z.number().int().min(1),
});
export type CycleCompletedV1Payload = z.infer<typeof CycleCompletedV1Payload>;
export const CycleCompletedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_COMPLETED"),
  schema_version: z.literal(1),
  payload: CycleCompletedV1Payload,
});

export const CyclePlanFallbackV1Payload = z.object({
  reason: z.string(),
});
export type CyclePlanFallbackV1Payload = z.infer<typeof CyclePlanFallbackV1Payload>;
export const CyclePlanFallbackV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_PLAN_FALLBACK"),
  schema_version: z.literal(1),
  payload: CyclePlanFallbackV1Payload,
});

export const CycleReviewedV1Payload = z.object({
  summary: z.string(),
});
export type CycleReviewedV1Payload = z.infer<typeof CycleReviewedV1Payload>;
export const CycleReviewedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_REVIEWED"),
  schema_version: z.literal(1),
  payload: CycleReviewedV1Payload,
});

export const CycleStageChangedV1Payload = z.object({
  from_stage: z.enum(["PLANNING", "EXECUTING", "MEASURING", "REVIEWING", "DONE"]),
  to_stage: z.enum(["PLANNING", "EXECUTING", "MEASURING", "REVIEWING", "DONE"]),
  deadline: z.iso.datetime({ offset: true }).nullable().default(null),
});
export type CycleStageChangedV1Payload = z.infer<typeof CycleStageChangedV1Payload>;
export const CycleStageChangedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_STAGE_CHANGED"),
  schema_version: z.literal(1),
  payload: CycleStageChangedV1Payload,
});

export const CycleStageTimeoutV1Payload = z.object({
  stage: z.enum(["PLANNING", "EXECUTING", "MEASURING", "REVIEWING", "DONE"]),
  cancelled_task_ids: z.array(z.uuid()).default(() => ([])),
});
export type CycleStageTimeoutV1Payload = z.infer<typeof CycleStageTimeoutV1Payload>;
export const CycleStageTimeoutV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_STAGE_TIMEOUT"),
  schema_version: z.literal(1),
  payload: CycleStageTimeoutV1Payload,
});

export const CycleStartedV1Payload = z.object({
  seq: z.number().int().min(1),
  stage: z.enum(["PLANNING", "EXECUTING", "MEASURING", "REVIEWING", "DONE"]),
  deadline: z.iso.datetime({ offset: true }).nullable().default(null),
});
export type CycleStartedV1Payload = z.infer<typeof CycleStartedV1Payload>;
export const CycleStartedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("CYCLE_STARTED"),
  schema_version: z.literal(1),
  payload: CycleStartedV1Payload,
});

export const EvidenceCapturedV1Payload = z.object({
  evidence_id: z.uuid(),
  url: z.string(),
  title: z.string().nullable().default(null),
  source_id: z.uuid().nullable().default(null),
  story_id: z.uuid().nullable().default(null),
});
export type EvidenceCapturedV1Payload = z.infer<typeof EvidenceCapturedV1Payload>;
export const EvidenceCapturedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("EVIDENCE_CAPTURED"),
  schema_version: z.literal(1),
  payload: EvidenceCapturedV1Payload,
});

export const ExpenseRecordedV1Payload = z.object({
  transaction_id: z.uuid(),
  project_id: z.uuid().nullable().default(null),
  category: z.string(),
  amount: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  currency: z.string().default("USD"),
});
export type ExpenseRecordedV1Payload = z.infer<typeof ExpenseRecordedV1Payload>;
export const ExpenseRecordedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("EXPENSE_RECORDED"),
  schema_version: z.literal(1),
  payload: ExpenseRecordedV1Payload,
});

export const GoalCreatedV1Payload = z.object({
  title: z.string(),
  level: z.enum(["annual", "quarter", "cycle"]),
  metric: z.string(),
  target: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  deadline: z.iso.datetime({ offset: true }).nullable().default(null),
  parent_goal_id: z.uuid().nullable().default(null),
});
export type GoalCreatedV1Payload = z.infer<typeof GoalCreatedV1Payload>;
export const GoalCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("GOAL_CREATED"),
  schema_version: z.literal(1),
  payload: GoalCreatedV1Payload,
});

export const GoalUpdatedV1Payload = z.object({
  current: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).nullable().default(null),
  target: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).nullable().default(null),
  status: z.enum(["active", "achieved", "missed", "cancelled"]).nullable().default(null),
});
export type GoalUpdatedV1Payload = z.infer<typeof GoalUpdatedV1Payload>;
export const GoalUpdatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("GOAL_UPDATED"),
  schema_version: z.literal(1),
  payload: GoalUpdatedV1Payload,
});

export const KpiSnapshotCreatedV1Payload = z.object({
  snapshot_id: z.uuid(),
  cycle_id: z.uuid().nullable().default(null),
  project_id: z.uuid().nullable().default(null),
  metrics: z.record(z.string(), z.unknown()),
});
export type KpiSnapshotCreatedV1Payload = z.infer<typeof KpiSnapshotCreatedV1Payload>;
export const KpiSnapshotCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("KPI_SNAPSHOT_CREATED"),
  schema_version: z.literal(1),
  payload: KpiSnapshotCreatedV1Payload,
});

export const PolicyDeniedV1Payload = z.object({
  action: z.string(),
  rule_id: z.string(),
  detail: z.string().nullable().default(null),
});
export type PolicyDeniedV1Payload = z.infer<typeof PolicyDeniedV1Payload>;
export const PolicyDeniedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("POLICY_DENIED"),
  schema_version: z.literal(1),
  payload: PolicyDeniedV1Payload,
});

export const PolicyUpdatedV1Payload = z.object({
  key: z.string(),
  value: z.unknown(),
  previous: z.unknown().default(null),
});
export type PolicyUpdatedV1Payload = z.infer<typeof PolicyUpdatedV1Payload>;
export const PolicyUpdatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("POLICY_UPDATED"),
  schema_version: z.literal(1),
  payload: PolicyUpdatedV1Payload,
});

export const ProjectApprovedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectApprovedV1Payload = z.infer<typeof ProjectApprovedV1Payload>;
export const ProjectApprovedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_APPROVED"),
  schema_version: z.literal(1),
  payload: ProjectApprovedV1Payload,
});

export const ProjectCompletedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectCompletedV1Payload = z.infer<typeof ProjectCompletedV1Payload>;
export const ProjectCompletedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_COMPLETED"),
  schema_version: z.literal(1),
  payload: ProjectCompletedV1Payload,
});

export const ProjectKilledV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectKilledV1Payload = z.infer<typeof ProjectKilledV1Payload>;
export const ProjectKilledV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_KILLED"),
  schema_version: z.literal(1),
  payload: ProjectKilledV1Payload,
});

export const ProjectKillProposedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
  approval_id: z.uuid().nullable().default(null),
});
export type ProjectKillProposedV1Payload = z.infer<typeof ProjectKillProposedV1Payload>;
export const ProjectKillProposedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_KILL_PROPOSED"),
  schema_version: z.literal(1),
  payload: ProjectKillProposedV1Payload,
});

export const ProjectPausedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
  trigger: z.enum(["human", "ceo", "kill_criteria"]).default("human"),
});
export type ProjectPausedV1Payload = z.infer<typeof ProjectPausedV1Payload>;
export const ProjectPausedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_PAUSED"),
  schema_version: z.literal(1),
  payload: ProjectPausedV1Payload,
});

export const ProjectProposedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectProposedV1Payload = z.infer<typeof ProjectProposedV1Payload>;
export const ProjectProposedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_PROPOSED"),
  schema_version: z.literal(1),
  payload: ProjectProposedV1Payload,
});

export const ProjectRejectedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectRejectedV1Payload = z.infer<typeof ProjectRejectedV1Payload>;
export const ProjectRejectedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_REJECTED"),
  schema_version: z.literal(1),
  payload: ProjectRejectedV1Payload,
});

export const ProjectResumedV1Payload = z.object({
  name: z.string(),
  reason: z.string().nullable().default(null),
});
export type ProjectResumedV1Payload = z.infer<typeof ProjectResumedV1Payload>;
export const ProjectResumedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("PROJECT_RESUMED"),
  schema_version: z.literal(1),
  payload: ProjectResumedV1Payload,
});

export const RevenueRecordedV1Payload = z.object({
  transaction_id: z.uuid(),
  project_id: z.uuid().nullable().default(null),
  category: z.string(),
  amount: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")),
  currency: z.string().default("USD"),
});
export type RevenueRecordedV1Payload = z.infer<typeof RevenueRecordedV1Payload>;
export const RevenueRecordedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("REVENUE_RECORDED"),
  schema_version: z.literal(1),
  payload: RevenueRecordedV1Payload,
});

export const ScheduleFiredV1Payload = z.object({
  schedule_name: z.string(),
  scheduled_for: z.iso.datetime({ offset: true }),
});
export type ScheduleFiredV1Payload = z.infer<typeof ScheduleFiredV1Payload>;
export const ScheduleFiredV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("SCHEDULE_FIRED"),
  schema_version: z.literal(1),
  payload: ScheduleFiredV1Payload,
});

export const SourceItemDiscoveredV1Payload = z.object({
  item_id: z.uuid(),
  source_id: z.uuid(),
  url: z.string(),
  title: z.string(),
});
export type SourceItemDiscoveredV1Payload = z.infer<typeof SourceItemDiscoveredV1Payload>;
export const SourceItemDiscoveredV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("SOURCE_ITEM_DISCOVERED"),
  schema_version: z.literal(1),
  payload: SourceItemDiscoveredV1Payload,
});

export const SourcePausedV1Payload = z.object({
  source_id: z.uuid(),
  reason: z.string(),
  failures: z.number().int(),
});
export type SourcePausedV1Payload = z.infer<typeof SourcePausedV1Payload>;
export const SourcePausedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("SOURCE_PAUSED"),
  schema_version: z.literal(1),
  payload: SourcePausedV1Payload,
});

export const SourcePolledV1Payload = z.object({
  source_id: z.uuid(),
  count: z.number().int(),
  seen: z.number().int().default(0),
  cost_usd: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).nullable().default(null),
  error: z.string().nullable().default(null),
});
export type SourcePolledV1Payload = z.infer<typeof SourcePolledV1Payload>;
export const SourcePolledV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("SOURCE_POLLED"),
  schema_version: z.literal(1),
  payload: SourcePolledV1Payload,
});

export const StrategyUpdatedV1Payload = z.object({
  summary: z.string(),
  approval_id: z.uuid().nullable().default(null),
});
export type StrategyUpdatedV1Payload = z.infer<typeof StrategyUpdatedV1Payload>;
export const StrategyUpdatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("STRATEGY_UPDATED"),
  schema_version: z.literal(1),
  payload: StrategyUpdatedV1Payload,
});

export const TaskBlockedV1Payload = z.object({
  reason: z.literal("budget"),
});
export type TaskBlockedV1Payload = z.infer<typeof TaskBlockedV1Payload>;
export const TaskBlockedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_BLOCKED"),
  schema_version: z.literal(1),
  payload: TaskBlockedV1Payload,
});

export const TaskCancelledV1Payload = z.object({
  reason: z.string(),
});
export type TaskCancelledV1Payload = z.infer<typeof TaskCancelledV1Payload>;
export const TaskCancelledV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_CANCELLED"),
  schema_version: z.literal(1),
  payload: TaskCancelledV1Payload,
});

export const TaskCreatedV1Payload = z.object({
  name: z.string(),
  display_name: z.string(),
  required_role: z.string(),
  depends_on: z.array(z.uuid()).default(() => ([])),
  workflow_run_id: z.uuid().nullable().default(null),
  budget_usd: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).nullable().default(null),
});
export type TaskCreatedV1Payload = z.infer<typeof TaskCreatedV1Payload>;
export const TaskCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_CREATED"),
  schema_version: z.literal(1),
  payload: TaskCreatedV1Payload,
});

export const TaskFailedV1Payload = z.object({
  run_id: z.uuid().nullable().default(null),
  final: z.boolean(),
  error_class: z.string(),
});
export type TaskFailedV1Payload = z.infer<typeof TaskFailedV1Payload>;
export const TaskFailedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_FAILED"),
  schema_version: z.literal(1),
  payload: TaskFailedV1Payload,
});

export const TaskReadyV1Payload = z.object({
  required_role: z.string(),
});
export type TaskReadyV1Payload = z.infer<typeof TaskReadyV1Payload>;
export const TaskReadyV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_READY"),
  schema_version: z.literal(1),
  payload: TaskReadyV1Payload,
});

export const TaskStartedV1Payload = z.object({
  run_id: z.uuid(),
  agent_id: z.uuid(),
  attempt: z.number().int().min(1),
});
export type TaskStartedV1Payload = z.infer<typeof TaskStartedV1Payload>;
export const TaskStartedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_STARTED"),
  schema_version: z.literal(1),
  payload: TaskStartedV1Payload,
});

export const TaskSucceededV1Payload = z.object({
  run_id: z.uuid().nullable().default(null),
  output_ref: z.string().nullable().default(null),
  unlocks: z.array(UnlockedTask).default(() => ([])),
});
export type TaskSucceededV1Payload = z.infer<typeof TaskSucceededV1Payload>;
export const TaskSucceededV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_SUCCEEDED"),
  schema_version: z.literal(1),
  payload: TaskSucceededV1Payload,
});

export const TaskWaitingV1Payload = z.object({
  reason: z.enum(["approval", "budget", "upstream", "rate_limit"]),
  approval_id: z.uuid().nullable().default(null),
});
export type TaskWaitingV1Payload = z.infer<typeof TaskWaitingV1Payload>;
export const TaskWaitingV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TASK_WAITING"),
  schema_version: z.literal(1),
  payload: TaskWaitingV1Payload,
});

export const ToolCalledV1Payload = z.object({
  tool: z.string(),
  tool_call_id: z.string(),
  args_summary: z.string().nullable().default(null),
  side_effect: z.enum(["read", "write", "irreversible"]),
  step_seq: z.number().int().min(0),
});
export type ToolCalledV1Payload = z.infer<typeof ToolCalledV1Payload>;
export const ToolCalledV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TOOL_CALLED"),
  schema_version: z.literal(1),
  payload: ToolCalledV1Payload,
});

export const ToolCompletedV1Payload = z.object({
  tool: z.string(),
  tool_call_id: z.string(),
  duration_ms: z.number().int().min(0),
  result_summary: z.string().nullable().default(null),
  cost_usd: z.string().regex(new RegExp("^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$")).nullable().default(null),
  produced: z.array(ProducedRef).default(() => ([])),
});
export type ToolCompletedV1Payload = z.infer<typeof ToolCompletedV1Payload>;
export const ToolCompletedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TOOL_COMPLETED"),
  schema_version: z.literal(1),
  payload: ToolCompletedV1Payload,
});

export const ToolDeniedV1Payload = z.object({
  tool: z.string(),
  tool_call_id: z.string(),
  decision: z.enum(["DENY", "NEEDS_APPROVAL"]),
  rule_id: z.string(),
  approval_id: z.uuid().nullable().default(null),
});
export type ToolDeniedV1Payload = z.infer<typeof ToolDeniedV1Payload>;
export const ToolDeniedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TOOL_DENIED"),
  schema_version: z.literal(1),
  payload: ToolDeniedV1Payload,
});

export const ToolFailedV1Payload = z.object({
  tool: z.string(),
  tool_call_id: z.string(),
  error_class: z.string(),
  message: z.string(),
  will_retry: z.boolean(),
});
export type ToolFailedV1Payload = z.infer<typeof ToolFailedV1Payload>;
export const ToolFailedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("TOOL_FAILED"),
  schema_version: z.literal(1),
  payload: ToolFailedV1Payload,
});

export const WorkflowRunCancelledV1Payload = z.object({
  duration_ms: z.number().int().min(0),
  reason: z.string(),
});
export type WorkflowRunCancelledV1Payload = z.infer<typeof WorkflowRunCancelledV1Payload>;
export const WorkflowRunCancelledV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("WORKFLOW_RUN_CANCELLED"),
  schema_version: z.literal(1),
  payload: WorkflowRunCancelledV1Payload,
});

export const WorkflowRunCompletedV1Payload = z.object({
  duration_ms: z.number().int().min(0),
});
export type WorkflowRunCompletedV1Payload = z.infer<typeof WorkflowRunCompletedV1Payload>;
export const WorkflowRunCompletedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("WORKFLOW_RUN_COMPLETED"),
  schema_version: z.literal(1),
  payload: WorkflowRunCompletedV1Payload,
});

export const WorkflowRunCreatedV1Payload = z.object({
  template: z.string(),
  params: z.record(z.string(), z.unknown()).default(() => ({})),
  project_id: z.uuid(),
  task_ids: z.array(z.uuid()),
});
export type WorkflowRunCreatedV1Payload = z.infer<typeof WorkflowRunCreatedV1Payload>;
export const WorkflowRunCreatedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("WORKFLOW_RUN_CREATED"),
  schema_version: z.literal(1),
  payload: WorkflowRunCreatedV1Payload,
});

export const WorkflowRunFailedV1Payload = z.object({
  duration_ms: z.number().int().min(0),
  failed_task_id: z.uuid().nullable().default(null),
  reason: z.string().nullable().default(null),
});
export type WorkflowRunFailedV1Payload = z.infer<typeof WorkflowRunFailedV1Payload>;
export const WorkflowRunFailedV1Event = z.object({
  ...envelopeFields,
  event_type: z.literal("WORKFLOW_RUN_FAILED"),
  schema_version: z.literal(1),
  payload: WorkflowRunFailedV1Payload,
});

export const EventEnvelope = z.discriminatedUnion("event_type", [
  AgentCreatedV1Event,
  AgentHeartbeatV1Event,
  AgentIdleV1Event,
  AgentPausedV1Event,
  AgentResumedV1Event,
  AgentReviewingV1Event,
  AgentRunAbortedV1Event,
  AgentRunCompletedV1Event,
  AgentRunFailedV1Event,
  AgentRunStartedV1Event,
  AgentStepProgressV1Event,
  AgentThinkingV1Event,
  AgentWaitingV1Event,
  AgentWorkingV1Event,
  ApprovalApprovedV1Event,
  ApprovalExpiredV1Event,
  ApprovalRejectedV1Event,
  ApprovalRequestedV1Event,
  BudgetAllocatedV1Event,
  BudgetExhaustedV1Event,
  CompanyCreatedV1Event,
  CycleCompletedV1Event,
  CyclePlanFallbackV1Event,
  CycleReviewedV1Event,
  CycleStageChangedV1Event,
  CycleStageTimeoutV1Event,
  CycleStartedV1Event,
  EvidenceCapturedV1Event,
  ExpenseRecordedV1Event,
  GoalCreatedV1Event,
  GoalUpdatedV1Event,
  KpiSnapshotCreatedV1Event,
  PolicyDeniedV1Event,
  PolicyUpdatedV1Event,
  ProjectApprovedV1Event,
  ProjectCompletedV1Event,
  ProjectKilledV1Event,
  ProjectKillProposedV1Event,
  ProjectPausedV1Event,
  ProjectProposedV1Event,
  ProjectRejectedV1Event,
  ProjectResumedV1Event,
  RevenueRecordedV1Event,
  ScheduleFiredV1Event,
  SourceItemDiscoveredV1Event,
  SourcePausedV1Event,
  SourcePolledV1Event,
  StrategyUpdatedV1Event,
  TaskBlockedV1Event,
  TaskCancelledV1Event,
  TaskCreatedV1Event,
  TaskFailedV1Event,
  TaskReadyV1Event,
  TaskStartedV1Event,
  TaskSucceededV1Event,
  TaskWaitingV1Event,
  ToolCalledV1Event,
  ToolCompletedV1Event,
  ToolDeniedV1Event,
  ToolFailedV1Event,
  WorkflowRunCancelledV1Event,
  WorkflowRunCompletedV1Event,
  WorkflowRunCreatedV1Event,
  WorkflowRunFailedV1Event,
]);
export type EventEnvelope = z.infer<typeof EventEnvelope>;
export type EventType = EventEnvelope["event_type"];
export type EventOf<T extends EventType> = Extract<EventEnvelope, { event_type: T }>;

export const EVENT_TYPES = [
  "AGENT_CREATED",
  "AGENT_HEARTBEAT",
  "AGENT_IDLE",
  "AGENT_PAUSED",
  "AGENT_RESUMED",
  "AGENT_REVIEWING",
  "AGENT_RUN_ABORTED",
  "AGENT_RUN_COMPLETED",
  "AGENT_RUN_FAILED",
  "AGENT_RUN_STARTED",
  "AGENT_STEP_PROGRESS",
  "AGENT_THINKING",
  "AGENT_WAITING",
  "AGENT_WORKING",
  "APPROVAL_APPROVED",
  "APPROVAL_EXPIRED",
  "APPROVAL_REJECTED",
  "APPROVAL_REQUESTED",
  "BUDGET_ALLOCATED",
  "BUDGET_EXHAUSTED",
  "COMPANY_CREATED",
  "CYCLE_COMPLETED",
  "CYCLE_PLAN_FALLBACK",
  "CYCLE_REVIEWED",
  "CYCLE_STAGE_CHANGED",
  "CYCLE_STAGE_TIMEOUT",
  "CYCLE_STARTED",
  "EVIDENCE_CAPTURED",
  "EXPENSE_RECORDED",
  "GOAL_CREATED",
  "GOAL_UPDATED",
  "KPI_SNAPSHOT_CREATED",
  "POLICY_DENIED",
  "POLICY_UPDATED",
  "PROJECT_APPROVED",
  "PROJECT_COMPLETED",
  "PROJECT_KILLED",
  "PROJECT_KILL_PROPOSED",
  "PROJECT_PAUSED",
  "PROJECT_PROPOSED",
  "PROJECT_REJECTED",
  "PROJECT_RESUMED",
  "REVENUE_RECORDED",
  "SCHEDULE_FIRED",
  "SOURCE_ITEM_DISCOVERED",
  "SOURCE_PAUSED",
  "SOURCE_POLLED",
  "STRATEGY_UPDATED",
  "TASK_BLOCKED",
  "TASK_CANCELLED",
  "TASK_CREATED",
  "TASK_FAILED",
  "TASK_READY",
  "TASK_STARTED",
  "TASK_SUCCEEDED",
  "TASK_WAITING",
  "TOOL_CALLED",
  "TOOL_COMPLETED",
  "TOOL_DENIED",
  "TOOL_FAILED",
  "WORKFLOW_RUN_CANCELLED",
  "WORKFLOW_RUN_COMPLETED",
  "WORKFLOW_RUN_CREATED",
  "WORKFLOW_RUN_FAILED",
] as const satisfies readonly EventType[];

export const EPHEMERAL_EVENT_TYPES: ReadonlySet<EventType> = new Set<EventType>([
  "AGENT_HEARTBEAT",
  "AGENT_STEP_PROGRESS",
]);
